steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloud-a3-454015/cloud-a3/validate:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry (AR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cloud-a3-454015/cloud-a3/validate:$SHORT_SHA']

  # Step 3: Configure kubectl with the GKE Cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'cloud-a3-cluster'
      - '--zone'
      - 'us-central1'
      - '--project'
      - 'cloud-a3-454015'

  # Step 4: Create Persistent Volume Claim (PVC)
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'pv-claim.yaml'

  # Step 5: Deploy the application and service to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'

   # Force the pods to restart with the new image (using the unique tag)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/validate-app', 'validate=us-central1-docker.pkg.dev/cloud-a3-454015/cloud-a3/validate:$SHORT_SHA']

# Define images for Cloud Build
images:
  - 'us-central1-docker.pkg.dev/cloud-a3-454015/cloud-a3/validate:$SHORT_SHA'

options:
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-a3'
  logging: CLOUD_LOGGING_ONLY