apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validate-app
  template:
    metadata:
      labels:
        app: validate-app
    spec:
      containers:
      - name: validate
        image: us-central1-docker.pkg.dev/cloud-a3-454015/cloud-a3/validate
        volumeMounts:
        - mountPath: /nakul_PV_dir
          name: cloud-a3-volume
        ports:
        - containerPort: 6000
      volumes:
      - name: cloud-a3-volume
        persistentVolumeClaim:
          claimName: cloud-a3-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: validate-service
spec:
  selector:
    app: validate-app
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer